from __future__ import annotations

TOKEN_PII_EMAIL = "[REDACTED_EMAIL]"
TOKEN_PII_DNI_NIF = "[REDACTED_DNI_NIF]"
TOKEN_PII_TELEFONO = "[REDACTED_PHONE]"
TOKEN_PII_HISTORIA_CLINICA = "[REDACTED_HISTORIA_CLINICA]"
TOKEN_PII_DIRECCION = "[REDACTED_DIRECCION]"
TOKEN_PII_CAMPO_SENSIBLE = "[REDACTED_FIELD]"

PLACEHOLDERS_PII_CANONICOS: frozenset[str] = frozenset(
    {
        TOKEN_PII_EMAIL,
        TOKEN_PII_DNI_NIF,
        TOKEN_PII_TELEFONO,
        TOKEN_PII_HISTORIA_CLINICA,
        TOKEN_PII_DIRECCION,
        TOKEN_PII_CAMPO_SENSIBLE,
    }
)

