from clinicdesk.app.application.seguros.fit_comercial import MotorFitComercialSeguro, SolicitudFitComercialSeguro
from clinicdesk.app.application.seguros.catalogo_planes import CatalogoPlanesSeguro
from clinicdesk.app.application.seguros.scoring_comercial import (
    AccionComercialSugerida,
    BandaPropensionSeguro,
    CarteraPriorizadaSeguro,
    NivelPrioridadComercialSeguro,
    PrediccionComercialSeguro,
    PrioridadOportunidadSeguro,
    ScoringComercialSeguroService,
    SemaforoComercialSeguro,
)
from clinicdesk.app.application.seguros.recomendacion_producto import (
    AccionRetencionSeguro,
    ArgumentoComercialSeguro,
    DiagnosticoComercialSeguro,
    MotivoRecomendacionPlan,
    RecomendacionPlanSeguro,
    RecomendadorProductoSeguroService,
    RiesgoRenovacionSeguro,
    SemaforoRenovacionSeguro,
)
from clinicdesk.app.application.seguros.cola_trabajo import (
    ColaTrabajoSeguroService,
    SolicitudGestionItemColaSeguro,
)
from clinicdesk.app.application.seguros.comercial import (
    FiltroCarteraSeguro,
    GestionComercialSeguroService,
    SolicitudNuevaOportunidadSeguro,
)
from clinicdesk.app.application.seguros.usecases import (
    AnalizarMigracionSeguroUseCase,
    RespuestaAnalisisMigracionSeguro,
    SolicitudAnalisisMigracionSeguro,
)
from clinicdesk.app.application.seguros.campanias import (
    GestionCampaniasSeguroService,
    SolicitudCrearCampaniaSeguro,
    SolicitudCrearCampaniaDesdeSugerencia,
    SolicitudGestionItemCampaniaSeguro,
)
from clinicdesk.app.application.seguros.analitica_ejecutiva import (
    AnaliticaEjecutivaSegurosService,
    CampaniaAccionableSeguro,
    CohorteSeguro,
    EstadoEmbudoSeguro,
    GrupoRenovacionSeguro,
    InsightComercialSeguro,
    MetricaFunnelSeguro,
    ResumenEjecutivoSeguros,
)
from clinicdesk.app.application.seguros.aprendizaje_comercial import AprendizajeComercialSegurosService
from clinicdesk.app.application.seguros.economia_valor import (
    CampaniaRentableSeguro,
    CategoriaValorEsperadoSeguro,
    EconomiaValorSeguroService,
    InsightRentabilidadSeguro,
    MargenEsperadoPlanSeguro,
    NivelCautelaEconomicaSeguro,
    PanelValorEconomicoSeguro,
    PrioridadValorSeguro,
    RiesgoEconomicoSeguro,
    SegmentoRentableSeguro,
    ValorEsperadoOportunidadSeguro,
)
from clinicdesk.app.application.seguros.forecast_comercial import ForecastComercialSeguroService
from clinicdesk.app.application.seguros.forecast_contratos import (
    DesvioObjetivoSeguro,
    EscenarioComercialSeguro,
    EstadoObjetivoSeguro,
    ForecastComercialSeguro,
    HorizonteForecastSeguro,
    NivelCautelaForecastSeguro,
    ObjetivoComercialSeguro,
    ProyeccionCampaniaSeguro,
    ProyeccionCohorteSeguro,
    RecomendacionEstrategicaSeguro,
)
from clinicdesk.app.application.seguros.aprendizaje_contratos import (
    EfectividadCampaniaSeguro,
    InsightArgumentoSeguro,
    InsightPlanSeguro,
    InsightSegmentoSeguro,
    MetricaAprendizajeComercialSeguro,
    PanelAprendizajeComercialSeguro,
    PlaybookComercialSeguro,
    RecomendacionCampaniaSeguro,
)

__all__ = [
    "CatalogoPlanesSeguro",
    "AnalizarMigracionSeguroUseCase",
    "SolicitudAnalisisMigracionSeguro",
    "RespuestaAnalisisMigracionSeguro",
    "GestionComercialSeguroService",
    "SolicitudNuevaOportunidadSeguro",
    "FiltroCarteraSeguro",
    "ColaTrabajoSeguroService",
    "SolicitudGestionItemColaSeguro",
    "MotorFitComercialSeguro",
    "SolicitudFitComercialSeguro",
    "ScoringComercialSeguroService",
    "PrediccionComercialSeguro",
    "PrioridadOportunidadSeguro",
    "AccionComercialSugerida",
    "SemaforoComercialSeguro",
    "NivelPrioridadComercialSeguro",
    "BandaPropensionSeguro",
    "CarteraPriorizadaSeguro",
    "RecomendadorProductoSeguroService",
    "RecomendacionPlanSeguro",
    "RiesgoRenovacionSeguro",
    "SemaforoRenovacionSeguro",
    "MotivoRecomendacionPlan",
    "ArgumentoComercialSeguro",
    "AccionRetencionSeguro",
    "DiagnosticoComercialSeguro",
    "AnaliticaEjecutivaSegurosService",
    "ResumenEjecutivoSeguros",
    "CohorteSeguro",
    "MetricaFunnelSeguro",
    "EstadoEmbudoSeguro",
    "CampaniaAccionableSeguro",
    "GrupoRenovacionSeguro",
    "InsightComercialSeguro",
    "GestionCampaniasSeguroService",
    "SolicitudCrearCampaniaSeguro",
    "SolicitudCrearCampaniaDesdeSugerencia",
    "SolicitudGestionItemCampaniaSeguro",
    "AprendizajeComercialSegurosService",
    "PanelAprendizajeComercialSeguro",
    "EfectividadCampaniaSeguro",
    "InsightArgumentoSeguro",
    "InsightPlanSeguro",
    "InsightSegmentoSeguro",
    "PlaybookComercialSeguro",
    "RecomendacionCampaniaSeguro",
    "MetricaAprendizajeComercialSeguro",
    "ForecastComercialSeguroService",
    "ForecastComercialSeguro",
    "EscenarioComercialSeguro",
    "ObjetivoComercialSeguro",
    "DesvioObjetivoSeguro",
    "RecomendacionEstrategicaSeguro",
    "ProyeccionCampaniaSeguro",
    "ProyeccionCohorteSeguro",
    "HorizonteForecastSeguro",
    "EstadoObjetivoSeguro",
    "NivelCautelaForecastSeguro",
    "EconomiaValorSeguroService",
    "PanelValorEconomicoSeguro",
    "ValorEsperadoOportunidadSeguro",
    "MargenEsperadoPlanSeguro",
    "RiesgoEconomicoSeguro",
    "PrioridadValorSeguro",
    "InsightRentabilidadSeguro",
    "CampaniaRentableSeguro",
    "SegmentoRentableSeguro",
    "CategoriaValorEsperadoSeguro",
    "NivelCautelaEconomicaSeguro",
]
